version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/codebattle
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
